name: skillupai-ml-tokyo8-20181023
channels:
  - conda-forge
dependencies:
  - python=3.6.6
  - python-graphviz=0.8.4
  - pip:
    - numpy==1.15.2
    - jupyter==1.0.0
    - scikit-learn==0.20.0
    - pandas==0.23.4
    - matplotlib==3.0.0
    - seaborn==0.8.1
    - pydotplus==2.0.2
    - graphviz==0.8.4
    - tensorflow==1.11.0
    - keras==2.2.4
